"""Simple wrappers for `pystata`/`sfi` functionality"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_runstata.ipynb.

# %% auto 0
__all__ = ['get_local', 'set_local', 'get_global', 'get_scalar', 'stata_formatted', 'variable_names', 'drop_var', 'obs_count',
           'pwd', 'macro_expand', 'run_direct', 'run_single']

# %% ../nbs/02_runstata.ipynb 5
from .misc_utils import print_red
from contextlib import redirect_stdout
from io import StringIO

import pystata

if __name__ == "__main__":
    from sfi import Data, Macro, Scalar, SFIToolkit

# %% ../nbs/02_runstata.ipynb 9
def get_local(name):
    return Macro.getLocal(name)

# %% ../nbs/02_runstata.ipynb 11
def set_local(name, value):
    return Macro.setLocal(name, value)

# %% ../nbs/02_runstata.ipynb 13
def get_global(name):
    return Macro.getGlobal(name)

# %% ../nbs/02_runstata.ipynb 15
def get_scalar(name):
    return Scalar.getValue(name)

# %% ../nbs/02_runstata.ipynb 17
def stata_formatted(value, s_format):
    return SFIToolkit.formatValue(value, s_format)

# %% ../nbs/02_runstata.ipynb 19
def variable_names():
    return [Data.getVarName(i) for i in range(Data.getVarCount())]

# %% ../nbs/02_runstata.ipynb 23
def drop_var(name):
    Data.dropVar(name)

# %% ../nbs/02_runstata.ipynb 26
def obs_count():
    """Count the number of observations"""
    return Data.getObsTotal()

# %% ../nbs/02_runstata.ipynb 29
def pwd():
    return SFIToolkit.getWorkingDir()

# %% ../nbs/02_runstata.ipynb 32
def macro_expand(s):
    return SFIToolkit.macroExpand(s)

# %% ../nbs/02_runstata.ipynb 35
def run_direct(cmds, quietly=False, echo=False, inline=True):
    # print(f"pystata module: {pystata}")
    # print(f"pystata file: {pystata.__file__}")
    # print(f"pystata attributes: {dir(pystata)}")
    return pystata.stata.run(cmds, quietly, echo, inline)

# %% ../nbs/02_runstata.ipynb 43
def run_single(cmd, echo=False):
    try:
        SFIToolkit.stata(cmd, echo)
    except Exception as e:
        with redirect_stdout(StringIO()) as diverted:
            SFIToolkit.stata("", echo)
        raise SyntaxError(diverted.getvalue())
